version: '3.1'
services:
  api-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-server
    environment:
      - CONNEXION_SERVER=
      - CONNEXION_DEBUG=True
      - API_SERVER_HOST=localhost
      - API_SERVER_PORT=5000
      - API_SERVER_KEYFILE=
      - API_SERVER_CERTFILE=
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=cmaq
      - POSTGRES_USERNAME=datatrans
      - POSTGRES_PASSWORD=datatrans
      - POSTGRES_IP=
      - SWAGGER_HOST=localhost:5000
    ports:
      - '5000:5000'
    networks:
      - cmaq_exposure_api
    restart: always

networks:
  cmaq_exposure_api: